---
functional:
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность играть с любым человеком, ботом или другом, приглашенным по ссылке
  - Пользователь должен иметь возможность доиграть до конца в случае его поражения или выхода соперника из игры
  - Пользователь должен иметь возможность видеть, кто является победителем игры после ее завершения
  - Пользователь, покинувший игру, должен иметь возможность переподключиться в игру пока она не закончена
  - Пользователь должен иметь возможность получать рейтинг за неделю, месяц и за все время
  - Пользователь должен иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность выбирать игру по уровню сложности и задачам
  - Пользователь должен иметь возможность выбирать длительность игры
  - Пользователь должен иметь возможность просмотра за ходом игр других пользователей
  - Пользователь должен иметь возможность просмотра код своего соперника в режиме онлайн
  - Пользователь должен иметь возможность проверки своего решение
  - Пользователь должен иметь возможность переходить в чат для общения зарегистрированных пользователей
  - Пользователь должен иметь возможность выйти из игры
  - Пользователь должен иметь возможность просматривать завершенную игру

non-functional:
  - Сайт должен разрабатываться с учетом удобства использования и быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
  - Пользователь должен иметь возможность переключать язык при просмотре задачи

implicit:
  - Сайт должен корректно отображаться при низкой скорости загрузки
  - Форма авторизации имеет защиту от ввода невалидных данных

